#ifndef SYNOERROR_H
#define SYNOERROR_H

#include <QMetaEnum>
#include <QObject>

class SynoErrorGadget : public QObject
{
    Q_OBJECT
    Q_DISABLE_COPY(SynoErrorGadget)

public:
    enum SynoError {
        // WEBAPI
        WEBAPI_ERR_NONE = 0,
        WEBAPI_ERR_UNKNOWN = 100,
        WEBAPI_ERR_BAD_REQUEST = 101,
        WEBAPI_ERR_NO_SUCH_API = 102,
        WEBAPI_ERR_NO_SUCH_METHOD = 103,
        WEBAPI_ERR_NOT_SUPPORTED_VERSION = 104,
        WEBAPI_ERR_NO_PERMISSION = 105,
        WEBAPI_ERR_SESSION_TIMEOUT = 106,
        WEBAPI_ERR_SESSION_INTERRUPT = 107,
        WEBAPI_ERR_CUSTOMIZED_MIN = 400,

        // SYNO.PhotoStation.Info (401-405)

        // SYNO.PhotoStation.Auth (406-415)
        PHOTOSTATION_AUTH_LOGIN_NOPRIVILEGE = 406,
        PHOTOSTATION_AUTH_LOGIN_ERROR = 407,
        PHOTOSTATION_AUTH_LOGIN_DISABLE_ACCOUNT = 408,
        PHOTOSTATION_AUTH_LOGIN_GUEST_ERROR = 409,
        PHOTOSTATION_AUTH_LOGIN_MAX_TRIES = 410,

        // SYNO.PhotoStaion.Album (416-425)
        PHOTOSTATION_ALBUM_PASSWORD_ERROR = 416,
        PHOTOSTATION_ALBUM_NO_ACCESS_RIGHT = 417,
        PHOTOSTATION_ALBUM_NO_UPLOAD_RIGHT = 418,
        PHOTOSTATION_ALBUM_NO_MANAGE_RIGHT = 419,
        PHOTOSTATION_ALBUM_NOT_ADMIN = 420,
        PHOTOSTATION_ALBUM_HAS_EXIST = 421,
        PHOTOSTATION_ALBUM_CREATE_FAIL = 422,
        PHOTOSTATION_ALBUM_EDIT_FAIL = 423,
        PHOTOSTATION_ALBUM_DELETE_FAIL = 424,
        PHOTOSTATION_ALBUM_SELECT_CONFLICT = 425,

        // SYNO.PhotoStation.Permission (426-435)
        PHOTOSTATION_PERMISSION_BAD_PARAMS = 426,
        PHOTOSTATION_PERMISSION_ACCESS_DENY = 427,

        // SYNO.PhotoStation.Tag (436-445)
        PHOTOSTATION_TAG_LIST_FAIL = 436,
        PHOTOSTATION_TAG_GETINFO_FAIL = 437,
        PHOTOSTATION_TAG_CREATE_FAIL = 438,
        PHOTOSTATION_TAG_EDIT_FAIL = 439,
        PHOTOSTATION_TAG_ACCESS_DENY = 440,
        PHOTOSTATION_TAG_HAS_EXIST = 441,
        PHOTOSTATION_TAG_SEARCH_FAIL = 442,

        // SYNO.PhotoStation.SmartAlbum (446-455)
        PHOTOSTATION_SMARTALBUM_CREATE_FAIL = 446,
        PHOTOSTATION_SMARTALBUM_EDIT_FAIL = 447,
        PHOTOSTATION_SMARTALBUM_ACCESS_DENY = 448,
        PHOTOSTATION_SMARTALBUM_NOT_EXIST = 449,
        PHOTOSTATION_SMARTALBUM_TAG_NOT_EXIST = 450,
        PHOTOSTATION_SMARTALBUM_CREATE_FAIL_EXIST = 451,

        // SYNO.PhotoStation.Photo (456-465)
        PHOTOSTATION_PHOTO_BAD_PARAMS = 456,
        PHOTOSTATION_PHOTO_ACCESS_DENY = 457,
        PHOTOSTATION_PHOTO_SELECT_CONFLICT = 458,

        // SYNO.PhotoStation.PhotoTag (466-475)
        PHOTOSTATION_PHOTO_TAG_ACCESS_DENY = 466,
        PHOTOSTATION_PHOTO_TAG_NOT_EXIST = 467,
        PHOTOSTATION_PHOTO_TAG_DUPLICATE = 468,
        PHOTOSTATION_PHOTO_TAG_VIDEO_NOT_EXIST = 469,
        PHOTOSTATION_PHOTO_TAG_ADD_GEO_DESC_FAIL = 470,
        PHOTOSTATION_PHOTO_TAG_ADD_PEOPLE_FAIL = 471,
        PHOTOSTATION_PHOTO_TAG_DELETE_FAIL = 472,
        PHOTOSTATION_PHOTO_TAG_PEOPLE_TAG_CONFIRM_FAIL = 473,

        // SYNO.PhotoStation.Category (476-490)
        PHOTOSTATION_CATEGORY_ACCESS_DENY = 476,
        PHOTOSTATION_CATEGORY_WRONG_ID_FORMAT = 477,
        PHOTOSTATION_CATEGORY_GETINFO_FAIL = 478,
        PHOTOSTATION_CATEGORY_CREATE_FAIL = 479,
        PHOTOSTATION_CATEGORY_DELETE_FAIL = 480,
        PHOTOSTATION_CATEGORY_EDIT_FAIL = 481,
        PHOTOSTATION_CATEGORY_ARRANGE_FAIL = 482,
        PHOTOSTATION_CATEGORY_ADD_ITEM_FAIL = 483,
        PHOTOSTATION_CATEGORY_LIST_ITEM_FAIL = 484,
        PHOTOSTATION_CATEGORY_REMOVE_ITEM_FAIL = 485,
        PHOTOSTATION_CATEGORY_ARRANGE_ITEM_FAIL = 486,
        PHOTOSTATION_CATEGORY_DUPLICATE = 487,

        // SYNO.PhotoStation.Comment (491-495)
        PHOTOSTATION_COMMENT_VALIDATE_FAIL = 491,
        PHOTOSTATION_COMMENT_ACCESS_DENY = 492,
        PHOTOSTATION_COMMENT_CREATE_FAIL = 493,

        // SYNO.PhotoStation.Thumb (496-505)
        PHOTOSTATION_THUMB_BAD_PARAMS = 501,
        PHOTOSTATION_THUMB_ACCESS_DENY = 502,
        PHOTOSTATION_THUMB_NO_COVER = 503,
        PHOTOSTATION_THUMB_FILE_NOT_EXISTS = 504,

        // SYNO.PhotoStation.Download (506-515)
        PHOTOSTATION_DOWNLOAD_BAD_PARAMS = 506,
        PHOTOSTATION_DOWNLOAD_ACCESS_DENY = 507,
        PHOTOSTATION_DOWNLOAD_CHDIR_ERROR = 508,

        // SYNO.PhotoStation.File (516-525)
        PHOTOSTATION_FILE_BAD_PARAMS = 516,
        PHOTOSTATION_FILE_ACCESS_DENY = 517,
        PHOTOSTATION_FILE_FILE_EXT_ERR = 518,
        PHOTOSTATION_FILE_DIR_NOT_EXISTS = 519,
        PHOTOSTATION_FILE_UPLOAD_ERROR = 520,
        PHOTOSTATION_FILE_NO_FILE = 521,
        PHOTOSTATION_FILE_UPLOAD_CANT_WRITE = 522,

        // SYNO.PhotoStation.Cover (526-530)
        PHOTOSTATION_COVER_ACCESS_DENY = 526,
        PHOTOSTATION_COVER_ALBUM_NOT_EXIST = 527,
        PHOTOSTATION_COVER_PHOTO_VIDEO_NOT_EXIST = 528,
        PHOTOSTATION_COVER_PHOTO_VIDEO_NOT_IN_ALBUM = 529,
        PHOTOSTATION_COVER_SET_FAIL = 530,

        // SYNO.PhotoStation.Rotate (531-535)
        PHOTOSTATION_ROTATE_ACCESS_DENY = 531,
        PHOTOSTATION_ROTATE_SET_FAIL = 532,

        // SYNO.PhotoStation.SlideshowMusic (536-545)
        PHOTOSTATION_SLIDESHOWMUSIC_ACCESS_DENY = 536,
        PHOTOSTATION_SLIDESHOWMUSIC_SET_FAIL = 537,
        PHOTOSTATION_SLIDESHOWMUSIC_FILE_EXT_ERR = 538,
        PHOTOSTATION_SLIDESHOWMUSIC_UPLOAD_ERROR = 539,
        PHOTOSTATION_SLIDESHOWMUSIC_NO_FILE = 540,
        PHOTOSTATION_SLIDESHOWMUSIC_EXCEED_LIMIT = 541,

        // SYNO.PhotoStation.DsmShare (546-550)
        PHOTOSTATION_DSMSHARE_UPLOAD_ERROR = 546,
        PHOTOSTATION_DSMSHARE_ACCESS_DENY = 547,

        // SYNO.PhotoStation.SharedAlbum (551-560)
        PHOTOSTATION_SHARED_ALBUM_ACCESS_DENY = 551,
        PHOTOSTATION_SHARED_ALBUM_BAD_PARAMS = 552,
        PHOTOSTATION_SHARED_ALBUM_HAS_EXISTED = 553,
        PHOTOSTATION_SHARED_ALBUM_CREATE_FAIL = 554,
        PHOTOSTATION_SHARED_ALBUM_NOT_EXISTS = 555,
        PHOTOSTATION_SHARED_ALBUM_GET_INFO_ERROR = 556,
        PHOTOSTATION_SHARED_ALBUM_LIST_ERROR = 557,

        // SYNO.PhotoStation.Log (561-565)
        PHOTOSTATION_LOG_ACCESS_DENY = 561,

        // SYNO.PhotoStation.PATH (566-570)
        PHOTOSTATION_PATH_ACCESS_DENY = 566,

        // SYNO.PhotoStation.ACL (571-580)
        PHOTOSTATION_ACL_NOT_SUPPORT = 571,
        PHOTOSTATION_ACL_CONVERT_FAIL = 572,

        // SYNO.PhotoStation.AdvancedShare (581-590)
        PHOTOSTATION_PHOTO_AREA_TAG_ADD_FAIL = 581,
        PHOTOSTATION_PHOTO_AREA_TAG_NOT_ENABLED = 582,
        PHOTOSTATION_PHOTO_AREA_TAG_DELETE_FAIL = 583
    };
    Q_ENUM(SynoError)

public:
    static QMetaEnum metaEnum();

private:
    explicit SynoErrorGadget(QObject *parent = nullptr);
};

#endif // SYNOERROR_H
